#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programowanie_Obiektowe___Projekt
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PROJEKT")]
	public partial class OderDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertItemy(Itemy instance);
    partial void UpdateItemy(Itemy instance);
    partial void DeleteItemy(Itemy instance);
    partial void InsertKategoria(Kategoria instance);
    partial void UpdateKategoria(Kategoria instance);
    partial void DeleteKategoria(Kategoria instance);
    #endregion
		
		public OderDataContext() : 
				base(global::Programowanie_Obiektowe___Projekt.Properties.Settings.Default.PROJEKTConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OderDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OderDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OderDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OderDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Itemy> Itemy
		{
			get
			{
				return this.GetTable<Itemy>();
			}
		}
		
		public System.Data.Linq.Table<Jaeger> Jaeger
		{
			get
			{
				return this.GetTable<Jaeger>();
			}
		}
		
		public System.Data.Linq.Table<Kategoria> Kategoria
		{
			get
			{
				return this.GetTable<Kategoria>();
			}
		}
		
		public System.Data.Linq.Table<Mechanic> Mechanic
		{
			get
			{
				return this.GetTable<Mechanic>();
			}
		}
		
		public System.Data.Linq.Table<Peacekeeper> Peacekeeper
		{
			get
			{
				return this.GetTable<Peacekeeper>();
			}
		}
		
		public System.Data.Linq.Table<Prapor> Prapor
		{
			get
			{
				return this.GetTable<Prapor>();
			}
		}
		
		public System.Data.Linq.Table<Ragman> Ragman
		{
			get
			{
				return this.GetTable<Ragman>();
			}
		}
		
		public System.Data.Linq.Table<Skier> Skier
		{
			get
			{
				return this.GetTable<Skier>();
			}
		}
		
		public System.Data.Linq.Table<Therapist> Therapist
		{
			get
			{
				return this.GetTable<Therapist>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Itemy")]
	public partial class Itemy : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nazwa;
		
		private System.Nullable<int> _KategoriaID;
		
		private EntityRef<Kategoria> _Kategoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    partial void OnKategoriaIDChanging(System.Nullable<int> value);
    partial void OnKategoriaIDChanged();
    #endregion
		
		public Itemy()
		{
			this._Kategoria = default(EntityRef<Kategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriaID", DbType="Int")]
		public System.Nullable<int> KategoriaID
		{
			get
			{
				return this._KategoriaID;
			}
			set
			{
				if ((this._KategoriaID != value))
				{
					if (this._Kategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKategoriaIDChanging(value);
					this.SendPropertyChanging();
					this._KategoriaID = value;
					this.SendPropertyChanged("KategoriaID");
					this.OnKategoriaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoria_Itemy", Storage="_Kategoria", ThisKey="KategoriaID", OtherKey="ID", IsForeignKey=true)]
		public Kategoria Kategoria
		{
			get
			{
				return this._Kategoria.Entity;
			}
			set
			{
				Kategoria previousValue = this._Kategoria.Entity;
				if (((previousValue != value) 
							|| (this._Kategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategoria.Entity = null;
						previousValue.Itemy.Remove(this);
					}
					this._Kategoria.Entity = value;
					if ((value != null))
					{
						value.Itemy.Add(this);
						this._KategoriaID = value.ID;
					}
					else
					{
						this._KategoriaID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jaeger")]
	public partial class Jaeger
	{
		
		private System.Nullable<int> _ItemID;
		
		private System.Nullable<int> _CenaSprzedaży;
		
		private System.Nullable<int> _CenaKupna;
		
		private System.Nullable<int> _Level;
		
		public Jaeger()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaSprzedaży", DbType="Int")]
		public System.Nullable<int> CenaSprzedaży
		{
			get
			{
				return this._CenaSprzedaży;
			}
			set
			{
				if ((this._CenaSprzedaży != value))
				{
					this._CenaSprzedaży = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaKupna", DbType="Int")]
		public System.Nullable<int> CenaKupna
		{
			get
			{
				return this._CenaKupna;
			}
			set
			{
				if ((this._CenaKupna != value))
				{
					this._CenaKupna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategoria")]
	public partial class Kategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Nazwa;
		
		private EntitySet<Itemy> _Itemy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNazwaChanging(string value);
    partial void OnNazwaChanged();
    #endregion
		
		public Kategoria()
		{
			this._Itemy = new EntitySet<Itemy>(new Action<Itemy>(this.attach_Itemy), new Action<Itemy>(this.detach_Itemy));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwa", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Nazwa
		{
			get
			{
				return this._Nazwa;
			}
			set
			{
				if ((this._Nazwa != value))
				{
					this.OnNazwaChanging(value);
					this.SendPropertyChanging();
					this._Nazwa = value;
					this.SendPropertyChanged("Nazwa");
					this.OnNazwaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoria_Itemy", Storage="_Itemy", ThisKey="ID", OtherKey="KategoriaID")]
		public EntitySet<Itemy> Itemy
		{
			get
			{
				return this._Itemy;
			}
			set
			{
				this._Itemy.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Itemy(Itemy entity)
		{
			this.SendPropertyChanging();
			entity.Kategoria = this;
		}
		
		private void detach_Itemy(Itemy entity)
		{
			this.SendPropertyChanging();
			entity.Kategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mechanic")]
	public partial class Mechanic
	{
		
		private System.Nullable<int> _ItemID;
		
		private System.Nullable<int> _CenaSprzedaży;
		
		private System.Nullable<int> _CenaKupna;
		
		private System.Nullable<int> _Level;
		
		public Mechanic()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaSprzedaży", DbType="Int")]
		public System.Nullable<int> CenaSprzedaży
		{
			get
			{
				return this._CenaSprzedaży;
			}
			set
			{
				if ((this._CenaSprzedaży != value))
				{
					this._CenaSprzedaży = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaKupna", DbType="Int")]
		public System.Nullable<int> CenaKupna
		{
			get
			{
				return this._CenaKupna;
			}
			set
			{
				if ((this._CenaKupna != value))
				{
					this._CenaKupna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Peacekeeper")]
	public partial class Peacekeeper
	{
		
		private System.Nullable<int> _ItemID;
		
		private System.Nullable<int> _CenaSprzedaży;
		
		private System.Nullable<int> _CenaKupna;
		
		private System.Nullable<int> _Level;
		
		public Peacekeeper()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaSprzedaży", DbType="Int")]
		public System.Nullable<int> CenaSprzedaży
		{
			get
			{
				return this._CenaSprzedaży;
			}
			set
			{
				if ((this._CenaSprzedaży != value))
				{
					this._CenaSprzedaży = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaKupna", DbType="Int")]
		public System.Nullable<int> CenaKupna
		{
			get
			{
				return this._CenaKupna;
			}
			set
			{
				if ((this._CenaKupna != value))
				{
					this._CenaKupna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prapor")]
	public partial class Prapor
	{
		
		private System.Nullable<int> _ItemID;
		
		private System.Nullable<int> _CenaSprzedaży;
		
		private System.Nullable<int> _CenaKupna;
		
		private System.Nullable<int> _Level;
		
		public Prapor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaSprzedaży", DbType="Int")]
		public System.Nullable<int> CenaSprzedaży
		{
			get
			{
				return this._CenaSprzedaży;
			}
			set
			{
				if ((this._CenaSprzedaży != value))
				{
					this._CenaSprzedaży = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaKupna", DbType="Int")]
		public System.Nullable<int> CenaKupna
		{
			get
			{
				return this._CenaKupna;
			}
			set
			{
				if ((this._CenaKupna != value))
				{
					this._CenaKupna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ragman")]
	public partial class Ragman
	{
		
		private System.Nullable<int> _ItemID;
		
		private System.Nullable<int> _CenaSprzedaży;
		
		private System.Nullable<int> _CenaKupna;
		
		private System.Nullable<int> _Level;
		
		public Ragman()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaSprzedaży", DbType="Int")]
		public System.Nullable<int> CenaSprzedaży
		{
			get
			{
				return this._CenaSprzedaży;
			}
			set
			{
				if ((this._CenaSprzedaży != value))
				{
					this._CenaSprzedaży = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaKupna", DbType="Int")]
		public System.Nullable<int> CenaKupna
		{
			get
			{
				return this._CenaKupna;
			}
			set
			{
				if ((this._CenaKupna != value))
				{
					this._CenaKupna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Skier")]
	public partial class Skier
	{
		
		private System.Nullable<int> _ItemID;
		
		private System.Nullable<int> _CenaSprzedaży;
		
		private System.Nullable<int> _CenaKupna;
		
		private System.Nullable<int> _Level;
		
		public Skier()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaSprzedaży", DbType="Int")]
		public System.Nullable<int> CenaSprzedaży
		{
			get
			{
				return this._CenaSprzedaży;
			}
			set
			{
				if ((this._CenaSprzedaży != value))
				{
					this._CenaSprzedaży = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaKupna", DbType="Int")]
		public System.Nullable<int> CenaKupna
		{
			get
			{
				return this._CenaKupna;
			}
			set
			{
				if ((this._CenaKupna != value))
				{
					this._CenaKupna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Therapist")]
	public partial class Therapist
	{
		
		private System.Nullable<int> _ItemID;
		
		private System.Nullable<int> _CenaSprzedaży;
		
		private System.Nullable<int> _CenaKupna;
		
		private System.Nullable<int> _Level;
		
		public Therapist()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemID", DbType="Int")]
		public System.Nullable<int> ItemID
		{
			get
			{
				return this._ItemID;
			}
			set
			{
				if ((this._ItemID != value))
				{
					this._ItemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaSprzedaży", DbType="Int")]
		public System.Nullable<int> CenaSprzedaży
		{
			get
			{
				return this._CenaSprzedaży;
			}
			set
			{
				if ((this._CenaSprzedaży != value))
				{
					this._CenaSprzedaży = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CenaKupna", DbType="Int")]
		public System.Nullable<int> CenaKupna
		{
			get
			{
				return this._CenaKupna;
			}
			set
			{
				if ((this._CenaKupna != value))
				{
					this._CenaKupna = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Level]", Storage="_Level", DbType="Int")]
		public System.Nullable<int> Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
